//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyBlog.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống gặp sự cố. Xin vui lòng quay lại sau.!.
        /// </summary>
        public static string alert_description {
            get {
                return ResourceManager.GetString("alert.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ôi không....
        /// </summary>
        public static string alert_title {
            get {
                return ResourceManager.GetString("alert.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sở thích.
        /// </summary>
        public static string home_body_favorite {
            get {
                return ResourceManager.GetString("home_body.favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌻 Chào buổi sáng! Chúc bạn một ngày mới tràn đầy năng lượng!.
        /// </summary>
        public static string home_body_greeting_day {
            get {
                return ResourceManager.GetString("home_body.greeting.day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào !.
        /// </summary>
        public static string home_body_hi {
            get {
                return ResourceManager.GetString("home_body.hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ của mình.
        /// </summary>
        public static string home_body_link_list_contact {
            get {
                return ResourceManager.GetString("home_body.link_list.contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý lịch của mình.
        /// </summary>
        public static string home_body_link_list_cv {
            get {
                return ResourceManager.GetString("home_body.link_list.cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các dự án mình làm.
        /// </summary>
        public static string home_body_link_list_projects {
            get {
                return ResourceManager.GetString("home_body.link_list.projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các tiện ích mình làm.
        /// </summary>
        public static string home_body_link_list_tools {
            get {
                return ResourceManager.GetString("home_body.link_list.tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn bạn đã ghé thăm ! ❤️.
        /// </summary>
        public static string home_body_thanks {
            get {
                return ResourceManager.GetString("home_body.thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string nav_contact {
            get {
                return ResourceManager.GetString("nav.contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý lịch.
        /// </summary>
        public static string nav_cv {
            get {
                return ResourceManager.GetString("nav.cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string nav_home {
            get {
                return ResourceManager.GetString("nav.home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án.
        /// </summary>
        public static string nav_project {
            get {
                return ResourceManager.GetString("nav.project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiện ích.
        /// </summary>
        public static string nav_tool {
            get {
                return ResourceManager.GetString("nav.tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuật toán.
        /// </summary>
        public static string projects_card_technical_algo {
            get {
                return ResourceManager.GetString("projects.card.technical.algo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiến trúc phần mềm.
        /// </summary>
        public static string projects_card_technical_arc {
            get {
                return ResourceManager.GetString("projects.card.technical.arc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý phía máy chủ.
        /// </summary>
        public static string projects_card_technical_be {
            get {
                return ResourceManager.GetString("projects.card.technical.be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nguồn.
        /// </summary>
        public static string projects_card_technical_code {
            get {
                return ResourceManager.GetString("projects.card.technical.code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập dữ liệu.
        /// </summary>
        public static string projects_card_technical_dataset {
            get {
                return ResourceManager.GetString("projects.card.technical.dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ sở dữ liệu.
        /// </summary>
        public static string projects_card_technical_db {
            get {
                return ResourceManager.GetString("projects.card.technical.db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả dự án.
        /// </summary>
        public static string projects_card_technical_description {
            get {
                return ResourceManager.GetString("projects.card.technical.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao diện người dùng.
        /// </summary>
        public static string projects_card_technical_fe {
            get {
                return ResourceManager.GetString("projects.card.technical.fe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khung phát triển.
        /// </summary>
        public static string projects_card_technical_framework {
            get {
                return ResourceManager.GetString("projects.card.technical.framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiến trúc hệ thống.
        /// </summary>
        public static string projects_card_technical_inf_str {
            get {
                return ResourceManager.GetString("projects.card.technical.inf_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ lập trình.
        /// </summary>
        public static string projects_card_technical_lang {
            get {
                return ResourceManager.GetString("projects.card.technical.lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư viện.
        /// </summary>
        public static string projects_card_technical_lib {
            get {
                return ResourceManager.GetString("projects.card.technical.lib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ số đánh giá.
        /// </summary>
        public static string projects_card_technical_metrics {
            get {
                return ResourceManager.GetString("projects.card.technical.metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma trận nhầm lẫn.
        /// </summary>
        public static string projects_card_technical_metrics_matrix {
            get {
                return ResourceManager.GetString("projects.card.technical.metrics.matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar.
        /// </summary>
        public static string projects_card_technical_metrics_scalar {
            get {
                return ResourceManager.GetString("projects.card.technical.metrics.scalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô hình sử dụng.
        /// </summary>
        public static string projects_card_technical_model {
            get {
                return ResourceManager.GetString("projects.card.technical.model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vai trò trong nhóm.
        /// </summary>
        public static string projects_card_technical_role {
            get {
                return ResourceManager.GetString("projects.card.technical.role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy mô dự án.
        /// </summary>
        public static string projects_card_technical_scope {
            get {
                return ResourceManager.GetString("projects.card.technical.scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại tác vụ.
        /// </summary>
        public static string projects_card_technical_task_type {
            get {
                return ResourceManager.GetString("projects.card.technical.task_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thử nghiệm.
        /// </summary>
        public static string projects_card_try {
            get {
                return ResourceManager.GetString("projects.card.try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách các dự án mình đã &amp; đang làm.
        /// </summary>
        public static string projects_description {
            get {
                return ResourceManager.GetString("projects.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string projects_filter_by_all {
            get {
                return ResourceManager.GetString("projects.filter_by.all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hoàn thành.
        /// </summary>
        public static string projects_filter_by_done {
            get {
                return ResourceManager.GetString("projects.filter_by.done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang thực hiện.
        /// </summary>
        public static string projects_filter_by_in_progress {
            get {
                return ResourceManager.GetString("projects.filter_by.in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm dự án....
        /// </summary>
        public static string projects_search_box_placeholder {
            get {
                return ResourceManager.GetString("projects.search_box.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án.
        /// </summary>
        public static string projects_title {
            get {
                return ResourceManager.GetString("projects.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn hỏi tôi điều gì ?.
        /// </summary>
        public static string question_body_content {
            get {
                return ResourceManager.GetString("question.body.content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viết gì đó vào đây....
        /// </summary>
        public static string question_body_content_placeholder {
            get {
                return ResourceManager.GetString("question.body.content_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email.
        /// </summary>
        public static string question_body_email {
            get {
                return ResourceManager.GetString("question.body.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên của bạn.
        /// </summary>
        public static string question_body_name {
            get {
                return ResourceManager.GetString("question.body.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viết gì đó vào đây....
        /// </summary>
        public static string question_body_placeholder {
            get {
                return ResourceManager.GetString("question.body.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi gửi câu hỏi. Vui lòng thử lại !.
        /// </summary>
        public static string question_body_response_fail {
            get {
                return ResourceManager.GetString("question.body.response.fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi của bạn đã được ghi nhận !.
        /// </summary>
        public static string question_body_response_success {
            get {
                return ResourceManager.GetString("question.body.response.success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi thông tin.
        /// </summary>
        public static string question_body_send {
            get {
                return ResourceManager.GetString("question.body.send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string question_close {
            get {
                return ResourceManager.GetString("question.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi câu hỏi của bạn.
        /// </summary>
        public static string question_header {
            get {
                return ResourceManager.GetString("question.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải mã.
        /// </summary>
        public static string tools_labels_base64_decode {
            get {
                return ResourceManager.GetString("tools.labels.base64.decode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hóa.
        /// </summary>
        public static string tools_labels_base64_encode {
            get {
                return ResourceManager.GetString("tools.labels.base64.encode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đầu ra.
        /// </summary>
        public static string tools_labels_base64_output {
            get {
                return ResourceManager.GetString("tools.labels.base64.output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nội dung để mã hóa/giải mã....
        /// </summary>
        public static string tools_labels_base64_placeholder {
            get {
                return ResourceManager.GetString("tools.labels.base64.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm lại.
        /// </summary>
        public static string tools_labels_img_pdf_clear {
            get {
                return ResourceManager.GetString("tools.labels.img_pdf.clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển đổi.
        /// </summary>
        public static string tools_labels_img_pdf_convert {
            get {
                return ResourceManager.GetString("tools.labels.img_pdf.convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tệp PDF.
        /// </summary>
        public static string tools_labels_img_pdf_output_file_name {
            get {
                return ResourceManager.GetString("tools.labels.img_pdf.output.file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng giấy.
        /// </summary>
        public static string tools_labels_img_pdf_output_orient {
            get {
                return ResourceManager.GetString("tools.labels.img_pdf.output.orient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khổ giấy.
        /// </summary>
        public static string tools_labels_img_pdf_output_paper_size {
            get {
                return ResourceManager.GetString("tools.labels.img_pdf.output.paper_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động tạo.
        /// </summary>
        public static string tools_labels_pwdgen_autorefresh {
            get {
                return ResourceManager.GetString("tools.labels.pwdgen.autorefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã sao chép vào clipboard !.
        /// </summary>
        public static string tools_labels_pwdgen_copied {
            get {
                return ResourceManager.GetString("tools.labels.pwdgen.copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao chép vào clipboard.
        /// </summary>
        public static string tools_labels_pwdgen_copy {
            get {
                return ResourceManager.GetString("tools.labels.pwdgen.copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tùy chỉnh cho mật khẩu.
        /// </summary>
        public static string tools_labels_pwdgen_customize {
            get {
                return ResourceManager.GetString("tools.labels.pwdgen.customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã tạo.
        /// </summary>
        public static string tools_labels_pwdgen_output {
            get {
                return ResourceManager.GetString("tools.labels.pwdgen.output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo lại mật khẩu.
        /// </summary>
        public static string tools_labels_pwdgen_refresh {
            get {
                return ResourceManager.GetString("tools.labels.pwdgen.refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn dạng mật khẩu.
        /// </summary>
        public static string tools_labels_pwdgen_type {
            get {
                return ResourceManager.GetString("tools.labels.pwdgen.type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kí tự.
        /// </summary>
        public static string tools_labels_qr_character {
            get {
                return ResourceManager.GetString("tools.labels.qr.character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu sắc.
        /// </summary>
        public static string tools_labels_qr_color {
            get {
                return ResourceManager.GetString("tools.labels.qr.color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải về máy.
        /// </summary>
        public static string tools_labels_qr_download {
            get {
                return ResourceManager.GetString("tools.labels.qr.download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chèn ảnh.
        /// </summary>
        public static string tools_labels_qr_image {
            get {
                return ResourceManager.GetString("tools.labels.qr.image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nội dung để tạo QR....
        /// </summary>
        public static string tools_labels_qr_placeholder {
            get {
                return ResourceManager.GetString("tools.labels.qr.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề con.
        /// </summary>
        public static string tools_labels_qr_subtitle {
            get {
                return ResourceManager.GetString("tools.labels.qr.subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string tools_labels_qr_title {
            get {
                return ResourceManager.GetString("tools.labels.qr.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm truy cập ẩn.
        /// </summary>
        public static string tools_labels_qr_wifi_hidden {
            get {
                return ResourceManager.GetString("tools.labels.qr.wifi.hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string tools_labels_qr_wifi_pwd {
            get {
                return ResourceManager.GetString("tools.labels.qr.wifi.pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu bảo mật.
        /// </summary>
        public static string tools_labels_qr_wifi_secure {
            get {
                return ResourceManager.GetString("tools.labels.qr.wifi.secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo QR cho kết nối Wifi.
        /// </summary>
        public static string tools_labels_qr_wifi_show {
            get {
                return ResourceManager.GetString("tools.labels.qr.wifi.show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSID.
        /// </summary>
        public static string tools_labels_qr_wifi_ssid {
            get {
                return ResourceManager.GetString("tools.labels.qr.wifi.ssid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm tiện ích....
        /// </summary>
        public static string tools_search_box_placeholder {
            get {
                return ResourceManager.GetString("tools.search_box.placeholder", resourceCulture);
            }
        }
    }
}
